### ISSUE TITLE
Getting error on deleting the plugin from the plugin page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#102] opened 2016-09-20 05:55 UTC
Deleting the plugin from the Plugin page, I am getting this error.
http://screencast.com/t/KpwDIpABLxqT

**Comment by Chetna1510** [comment] 2016-11-23 13:10
I have deleted the plugin from WordPress plugin's page. But I am not getting this error.

**Comment by Chetna1510** [comment] 2018-07-09 09:05
The issue is not for the latest version. So, I am closing this issue.

**Closed by Chetna1510** 2018-07-09 09:05 UTC
Labels: Major bug, Plugin delete, bug
